### ISSUE TITLE
v2.1.0-beta.16 occurs 'Maximum call stack size exceeded' Error

### ISSUE THREAD

**Issue by jhaemin** [paywteam/eodiro#262]
```
39|eodiro-client-dist  |  ERROR  Maximum call stack size exceeded
39|eodiro-client-dist  |   at Array.toString (<anonymous>)
39|eodiro-client-dist  |   at isSpecial (node_modules/deepmerge/dist/cjs.js:13:46)
39|eodiro-client-dist  |   at Object.isMergeableObject (node_modules/deepmerge/dist/cjs.js:5:7)
39|eodiro-client-dist  |   at cloneUnlessOtherwiseSpecified (node_modules/deepmerge/dist/cjs.js:33:45)
39|eodiro-client-dist  |   at node_modules/deepmerge/dist/cjs.js:94:23
39|eodiro-client-dist  |   at Array.forEach (<anonymous>)
39|eodiro-client-dist  |   at mergeObject (node_modules/deepmerge/dist/cjs.js:86:18)
39|eodiro-client-dist  |   at deepmerge (node_modules/deepmerge/dist/cjs.js:117:10)
39|eodiro-client-dist  |   at cloneUnlessOtherwiseSpecified (node_modules/deepmerge/dist/cjs.js:34:5)
39|eodiro-client-dist  |   at node_modules/deepmerge/dist/cjs.js:94:23
```

Thanks to @hchangjae

**Comment by jhaemin** [comment]
**Suspicious**

- Newly created `is-cached` module may generate loop through vuex store
